import { Category, Product, StoreConfig } from '@/types';
import { DEFAULT_STORE_CONFIG } from './delivery';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_staples',
    name: 'Atta, Rice & Dals',
    slug: 'staples-grains',
    iconName: 'Wheat',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80',
    sortOrder: 1,
    isActive: true,
    productCount: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_dairy',
    name: 'Dairy & Eggs',
    slug: 'dairy-eggs',
    iconName: 'Milk',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=400&q=80',
    sortOrder: 2,
    isActive: true,
    productCount: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_veggies',
    name: 'Fresh Vegetables & Fruits',
    slug: 'fruits-vegetables',
    iconName: 'Apple',
    image: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?auto=format&fit=crop&w=400&q=80',
    sortOrder: 3,
    isActive: true,
    productCount: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_oils',
    name: 'Oils & Ghee',
    slug: 'oils-ghee',
    iconName: 'Droplet',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80',
    sortOrder: 4,
    isActive: true,
    productCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_snacks',
    name: 'Snacks & Beverages',
    slug: 'snacks-beverages',
    iconName: 'Coffee',
    image: 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=400&q=80',
    sortOrder: 5,
    isActive: true,
    productCount: 4,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_spices',
    name: 'Masalas & Spices',
    slug: 'spices-masala',
    iconName: 'Flame',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=400&q=80',
    sortOrder: 6,
    isActive: true,
    productCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_household',
    name: 'Cleaning & Household',
    slug: 'household',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=400&q=80',
    sortOrder: 7,
    isActive: true,
    productCount: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cat_personal',
    name: 'Personal Care & Hygiene',
    slug: 'personal-care',
    iconName: 'HeartHandshake',
    image: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=400&q=80',
    sortOrder: 8,
    isActive: true,
    productCount: 3,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // STAPLES
  {
    id: 'prod_tata_salt',
    name: 'Tata Salt Vacuum Evaporated Iodized Salt',
    slug: 'tata-salt-1kg',
    sku: 'KP-STP-001',
    categoryId: 'cat_staples',
    categoryName: 'Atta, Rice & Dals',
    brand: 'Tata',
    description: 'Desh Ka Namak. Pure, vacuum-evaporated iodized salt ensuring adequate iodine intake for optimal health and mental development.',
    ingredients: 'Edible Common Salt, Potassium Iodate (30 ppm), Anti-caking agent (INS 551)',
    nutritionInfo: {
      energy: '0 kcal',
      protein: '0 g',
      carbs: '0 g',
      fat: '0 g',
    },
    barcode: '8901015000010',
    mrp: 30,
    sellingPrice: 26,
    discount: 13,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 45,
    lowStockThreshold: 10,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    tags: ['salt', 'tata', 'iodized', 'staples', 'namak'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1518110925495-5fe2fda0442c?auto=format&fit=crop&w=500&q=80',
        altText: 'Tata Salt 1kg Pack',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 28,
      blinkit: 30,
      zepto: 29,
      jiomart: 27,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_aashirvaad_atta',
    name: 'Aashirvaad Superior MP Sharbati Whole Wheat Atta',
    slug: 'aashirvaad-sharbati-atta-5kg',
    sku: 'KP-STP-002',
    categoryId: 'cat_staples',
    categoryName: 'Atta, Rice & Dals',
    brand: 'Aashirvaad',
    description: 'Made from the king of wheat — Madhya Pradesh Sharbati grains. Gives soft, fluffy rotis that stay tender for hours.',
    ingredients: '100% Whole Wheat Grain Flour',
    nutritionInfo: {
      energy: '360 kcal / 100g',
      protein: '11.5 g',
      carbs: '73 g',
      fat: '1.8 g',
      fiber: '11 g',
    },
    barcode: '8901030000021',
    mrp: 340,
    sellingPrice: 295,
    discount: 13,
    unit: 'kg',
    unitValue: 5,
    stockQuantity: 28,
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    tags: ['atta', 'flour', 'aashirvaad', 'sharbati', 'wheat', 'roti'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=500&q=80',
        altText: 'Aashirvaad Sharbati Atta 5kg',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 310,
      blinkit: 325,
      zepto: 320,
      jiomart: 305,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_india_gate_rice',
    name: 'India Gate Super Premium Basmati Rice',
    slug: 'india-gate-super-basmati-rice-1kg',
    sku: 'KP-STP-003',
    categoryId: 'cat_staples',
    categoryName: 'Atta, Rice & Dals',
    brand: 'India Gate',
    description: 'Aged basmati rice with slender long grains and exquisite fragrant aroma, ideal for biryani and festive pulao.',
    ingredients: '100% Aged Long Grain Basmati Rice',
    nutritionInfo: {
      energy: '350 kcal / 100g',
      protein: '8.8 g',
      carbs: '77 g',
      fat: '0.5 g',
      fiber: '1.2 g',
    },
    barcode: '8901058000034',
    mrp: 210,
    sellingPrice: 175,
    discount: 16,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 30,
    lowStockThreshold: 8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    tags: ['rice', 'basmati', 'india gate', 'biryani', 'staples'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80',
        altText: 'India Gate Basmati Rice',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 185,
      blinkit: 195,
      zepto: 190,
      jiomart: 180,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_tata_toor_dal',
    name: 'Tata Sampann Unpolished High Protein Toor Dal',
    slug: 'tata-sampann-toor-dal-1kg',
    sku: 'KP-STP-004',
    categoryId: 'cat_staples',
    categoryName: 'Atta, Rice & Dals',
    brand: 'Tata Sampann',
    description: 'Natural unpolished Toor / Arhar Dal sourced directly from farmers. Retains natural wholesome proteins and rich aroma.',
    ingredients: '100% Unpolished Arhar / Toor Dal',
    nutritionInfo: {
      energy: '343 kcal / 100g',
      protein: '22.3 g',
      carbs: '57 g',
      fat: '1.5 g',
      fiber: '15 g',
    },
    barcode: '8901015000045',
    mrp: 190,
    sellingPrice: 158,
    discount: 17,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 3, // Low stock demo!
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    tags: ['dal', 'toor dal', 'arhar', 'tata sampann', 'protein'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=500&q=80',
        altText: 'Tata Sampann Toor Dal 1kg',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 170,
      blinkit: 178,
      zepto: 175,
      jiomart: 165,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // DAIRY
  {
    id: 'prod_amul_butter',
    name: 'Amul Pasteurised Salted Table Butter',
    slug: 'amul-butter-500g',
    sku: 'KP-DRY-001',
    categoryId: 'cat_dairy',
    categoryName: 'Dairy & Eggs',
    brand: 'Amul',
    description: 'Utterly Butterly Delicious Amul Butter. Made from pure pasteurised cream with just the right pinch of salt.',
    ingredients: 'Butter (Milk Fat 80%), Common Salt (2.5%), Moisture (16%)',
    nutritionInfo: {
      energy: '722 kcal / 100g',
      protein: '0.6 g',
      carbs: '0 g',
      fat: '80 g',
    },
    barcode: '8901262010012',
    mrp: 290,
    sellingPrice: 275,
    discount: 5,
    unit: 'g',
    unitValue: 500,
    stockQuantity: 2, // Low stock demo!
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    tags: ['butter', 'amul', 'dairy', 'breakfast', 'toast'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=500&q=80',
        altText: 'Amul Butter 500g',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 285,
      blinkit: 290,
      zepto: 288,
      jiomart: 280,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_amul_milk',
    name: 'Amul Taaza Homogenised Toned Long-Life Milk',
    slug: 'amul-taaza-milk-1l',
    sku: 'KP-DRY-002',
    categoryId: 'cat_dairy',
    categoryName: 'Dairy & Eggs',
    brand: 'Amul',
    description: 'Fresh toned milk processed with ultra-high temperature (UHT) technology for safe storage without boiling.',
    ingredients: 'Toned Milk (Fat 3.0% minimum, SNF 8.5% minimum)',
    nutritionInfo: {
      energy: '58 kcal / 100ml',
      protein: '3.0 g',
      carbs: '4.7 g',
      fat: '3.0 g',
    },
    barcode: '8901262010029',
    mrp: 75,
    sellingPrice: 70,
    discount: 7,
    unit: 'L',
    unitValue: 1,
    stockQuantity: 40,
    lowStockThreshold: 10,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    tags: ['milk', 'amul', 'taaza', 'dairy', 'chai'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=500&q=80',
        altText: 'Amul Taaza Milk',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 74,
      blinkit: 75,
      zepto: 75,
      jiomart: 72,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_brown_eggs',
    name: 'Farm Fresh Organic Brown Protein Eggs',
    slug: 'farm-fresh-brown-eggs-6pcs',
    sku: 'KP-DRY-003',
    categoryId: 'cat_dairy',
    categoryName: 'Dairy & Eggs',
    brand: 'Farm Fresh',
    description: 'Grain-fed, antibiotic-free farm fresh brown eggs with rich golden yolks. Packed securely in biodegradable carton.',
    ingredients: 'Fresh Farm Eggs',
    nutritionInfo: {
      energy: '74 kcal / egg',
      protein: '6.3 g',
      carbs: '0.4 g',
      fat: '4.8 g',
    },
    barcode: '8901262010036',
    mrp: 65,
    sellingPrice: 54,
    discount: 17,
    unit: 'pack',
    unitValue: 6,
    stockQuantity: 25,
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    tags: ['eggs', 'brown eggs', 'protein', 'breakfast'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=500&q=80',
        altText: 'Fresh Brown Eggs 6 Pack',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 60,
      blinkit: 64,
      zepto: 62,
      jiomart: 58,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // VEGETABLES & FRUITS
  {
    id: 'prod_fresh_tomatoes',
    name: 'Fresh Farm Hybrid Ripe Tomatoes',
    slug: 'fresh-red-tomatoes-1kg',
    sku: 'KP-VEG-001',
    categoryId: 'cat_veggies',
    categoryName: 'Fresh Vegetables & Fruits',
    brand: 'Farm Fresh',
    description: 'Firm, juicy, deep-red garden fresh tomatoes. Hand-picked daily from local partner farms for curries and salads.',
    ingredients: '100% Fresh Tomatoes',
    nutritionInfo: {
      energy: '18 kcal / 100g',
      protein: '0.9 g',
      carbs: '3.9 g',
      fat: '0.2 g',
      fiber: '1.2 g',
    },
    barcode: '8904000100018',
    mrp: 40,
    sellingPrice: 28,
    discount: 30,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 50,
    lowStockThreshold: 10,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    tags: ['tomatoes', 'tamatar', 'vegetables', 'fresh', 'farm'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=500&q=80',
        altText: 'Fresh Tomatoes 1kg',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 34,
      blinkit: 38,
      zepto: 36,
      jiomart: 30,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_fresh_onions',
    name: 'Nashik Premium Red Onions',
    slug: 'fresh-nashik-onions-1kg',
    sku: 'KP-VEG-002',
    categoryId: 'cat_veggies',
    categoryName: 'Fresh Vegetables & Fruits',
    brand: 'Farm Fresh',
    description: 'Pungent, crisp and flavorful Nashik red onions with multiple layers. The backbone of every Indian tadka.',
    ingredients: '100% Fresh Red Onions',
    nutritionInfo: {
      energy: '40 kcal / 100g',
      protein: '1.1 g',
      carbs: '9.3 g',
      fat: '0.1 g',
      fiber: '1.7 g',
    },
    barcode: '8904000100025',
    mrp: 45,
    sellingPrice: 32,
    discount: 29,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 60,
    lowStockThreshold: 10,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    tags: ['onions', 'pyaz', 'vegetables', 'nashik', 'fresh'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=500&q=80',
        altText: 'Nashik Onions 1kg',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 38,
      blinkit: 42,
      zepto: 40,
      jiomart: 35,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_fresh_potatoes',
    name: 'Hill Fresh Mountain Jyoti Potatoes',
    slug: 'fresh-jyoti-potatoes-1kg',
    sku: 'KP-VEG-003',
    categoryId: 'cat_veggies',
    categoryName: 'Fresh Vegetables & Fruits',
    brand: 'Farm Fresh',
    description: 'Cleaned, thin-skinned mountain potatoes suitable for dry bhujia, curries, boiling, and roasting.',
    ingredients: '100% Fresh Potatoes',
    nutritionInfo: {
      energy: '77 kcal / 100g',
      protein: '2.0 g',
      carbs: '17 g',
      fat: '0.1 g',
      fiber: '2.2 g',
    },
    barcode: '8904000100032',
    mrp: 35,
    sellingPrice: 24,
    discount: 31,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 70,
    lowStockThreshold: 15,
    isActive: true,
    isFeatured: false,
    isDailyDeal: false,
    tags: ['potatoes', 'aloo', 'vegetables', 'fresh'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=500&q=80',
        altText: 'Fresh Potatoes 1kg',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 29,
      blinkit: 32,
      zepto: 30,
      jiomart: 26,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // OILS & GHEE
  {
    id: 'prod_fortune_sunflower_oil',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    slug: 'fortune-sunflower-oil-1l',
    sku: 'KP-OIL-001',
    categoryId: 'cat_oils',
    categoryName: 'Oils & Ghee',
    brand: 'Fortune',
    description: 'Light, clear and enriched with Vitamins A & D. Low absorption formula keeps your favorite fried snacks crisp and guilt-free.',
    ingredients: 'Refined Sunflower Oil, Vitamin A, Vitamin D',
    nutritionInfo: {
      energy: '900 kcal / 100ml',
      protein: '0 g',
      carbs: '0 g',
      fat: '100 g',
    },
    barcode: '8906007280011',
    mrp: 175,
    sellingPrice: 145,
    discount: 17,
    unit: 'L',
    unitValue: 1,
    stockQuantity: 35,
    lowStockThreshold: 8,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    tags: ['oil', 'sunflower oil', 'fortune', 'cooking oil'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=500&q=80',
        altText: 'Fortune Sunflower Oil 1L',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 155,
      blinkit: 168,
      zepto: 165,
      jiomart: 150,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_amul_cow_ghee',
    name: 'Amul Pure Aromatic Cow Ghee Tin',
    slug: 'amul-pure-cow-ghee-1l',
    sku: 'KP-OIL-002',
    categoryId: 'cat_oils',
    categoryName: 'Oils & Ghee',
    brand: 'Amul',
    description: 'Rich granular texture and tempting golden hue made from pure fresh cow milk fat. Enhances dal tadka, rotis, and sweets.',
    ingredients: 'Pure Milk Fat (Cow Ghee 99.7%)',
    nutritionInfo: {
      energy: '900 kcal / 100ml',
      protein: '0 g',
      carbs: '0 g',
      fat: '99.7 g',
    },
    barcode: '8901262010043',
    mrp: 680,
    sellingPrice: 620,
    discount: 9,
    unit: 'L',
    unitValue: 1,
    stockQuantity: 18,
    lowStockThreshold: 4,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    tags: ['ghee', 'amul', 'cow ghee', 'desi ghee', 'pure'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1608797178974-15b35a61dd75?auto=format&fit=crop&w=500&q=80',
        altText: 'Amul Pure Cow Ghee 1L',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 645,
      blinkit: 670,
      zepto: 660,
      jiomart: 630,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // SNACKS & BEVERAGES
  {
    id: 'prod_maggi_noodles',
    name: 'Maggi 2-Minute Masala Instant Noodles (Pack of 4)',
    slug: 'maggi-masala-noodles-pack-of-4',
    sku: 'KP-SNK-001',
    categoryId: 'cat_snacks',
    categoryName: 'Snacks & Beverages',
    brand: 'Maggi',
    description: 'India’s favorite instant snack. Signature spice tastemaker blend of 10 roasted spices cooked in just 2 minutes.',
    ingredients: 'Wheat Flour, Palm Oil, Salt, Tastemaker spices (Coriander, Cumin, Turmeric, Ginger, Fenugreek)',
    nutritionInfo: {
      energy: '310 kcal / serving',
      protein: '6.8 g',
      carbs: '44 g',
      fat: '12 g',
    },
    barcode: '8901058852319',
    mrp: 60,
    sellingPrice: 52,
    discount: 13,
    unit: 'pack',
    unitValue: 4,
    stockQuantity: 50,
    lowStockThreshold: 10,
    isActive: true,
    isFeatured: true,
    isDailyDeal: true,
    tags: ['maggi', 'noodles', 'snack', 'instant food'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80',
        altText: 'Maggi Masala Noodles',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 56,
      blinkit: 59,
      zepto: 58,
      jiomart: 54,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_tata_tea_gold',
    name: 'Tata Tea Gold Premium Assam Black Tea',
    slug: 'tata-tea-gold-500g',
    sku: 'KP-SNK-002',
    categoryId: 'cat_snacks',
    categoryName: 'Snacks & Beverages',
    brand: 'Tata Tea',
    description: 'Exquisite blend of strong Assam CTC tea enriched with gently rolled long leaves for an irresistible aroma and taste.',
    ingredients: '100% CTC Tea with Long Leaf Grains',
    nutritionInfo: {
      energy: '0 kcal (without milk/sugar)',
      protein: '0 g',
      carbs: '0 g',
      fat: '0 g',
    },
    barcode: '8901052000078',
    mrp: 350,
    sellingPrice: 299,
    discount: 15,
    unit: 'g',
    unitValue: 500,
    stockQuantity: 24,
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    tags: ['tea', 'chai', 'tata tea gold', 'assam tea'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80',
        altText: 'Tata Tea Gold 500g',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 320,
      blinkit: 335,
      zepto: 330,
      jiomart: 310,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // HOUSEHOLD & CLEANING
  {
    id: 'prod_surf_excel',
    name: 'Surf Excel Easy Wash Detergent Powder',
    slug: 'surf-excel-easy-wash-1kg',
    sku: 'KP-HSD-001',
    categoryId: 'cat_household',
    categoryName: 'Cleaning & Household',
    brand: 'Surf Excel',
    description: 'Superior stain removal formula works like magic on tough collar and cuff dirt in bucket and machine washes.',
    ingredients: 'Sodium Carbonate, Surfactants, Optical Brighteners, Fragrance',
    barcode: '8901030388219',
    mrp: 160,
    sellingPrice: 139,
    discount: 13,
    unit: 'kg',
    unitValue: 1,
    stockQuantity: 30,
    lowStockThreshold: 6,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    tags: ['surf excel', 'detergent', 'washing powder', 'cleaning'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=500&q=80',
        altText: 'Surf Excel Easy Wash 1kg',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 148,
      blinkit: 155,
      zepto: 152,
      jiomart: 142,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod_vim_liquid',
    name: 'Vim Dishwash Gel Lemon Anti-Bacterial',
    slug: 'vim-dishwash-gel-lemon-500ml',
    sku: 'KP-HSD-002',
    categoryId: 'cat_household',
    categoryName: 'Cleaning & Household',
    brand: 'Vim',
    description: 'Infused with the power of 100 lemons. 1 spoon cleans an entire sink full of oily vessels without leaving white residue.',
    ingredients: 'Active Surfactants, Lemon Extracts, Antibacterial Agents',
    barcode: '8901030388226',
    mrp: 130,
    sellingPrice: 108,
    discount: 17,
    unit: 'mL',
    unitValue: 500,
    stockQuantity: 28,
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: true,
    isDailyDeal: false,
    tags: ['vim', 'dishwash', 'gel', 'cleaning', 'lemon'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?auto=format&fit=crop&w=500&q=80',
        altText: 'Vim Liquid Gel 500ml',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 118,
      blinkit: 125,
      zepto: 122,
      jiomart: 112,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // PERSONAL CARE
  {
    id: 'prod_dettol_soap',
    name: 'Dettol Original Germ Protection Bathing Soap (Pack of 4)',
    slug: 'dettol-original-soap-pack-of-4',
    sku: 'KP-PRS-001',
    categoryId: 'cat_personal',
    categoryName: 'Personal Care & Hygiene',
    brand: 'Dettol',
    description: 'Trusted 99.9% germ protection soap enriched with moisturizing glycerin to keep family skin healthy, soft and clean.',
    ingredients: 'Sodium Palmate, Glycerin, Chloroxylenol, Fragrance',
    barcode: '8901030388233',
    mrp: 170,
    sellingPrice: 142,
    discount: 16,
    unit: 'pack',
    unitValue: 4,
    stockQuantity: 32,
    lowStockThreshold: 5,
    isActive: true,
    isFeatured: false,
    isDailyDeal: true,
    tags: ['dettol', 'soap', 'bath', 'hygiene', 'germ protection'],
    images: [
      {
        url: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?auto=format&fit=crop&w=500&q=80',
        altText: 'Dettol Soap 4 Pack',
        isPrimary: true,
        sortOrder: 1,
      },
    ],
    priceComparison: {
      bigbasket: 155,
      blinkit: 162,
      zepto: 160,
      jiomart: 148,
      fetchedAt: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
